# Generated by Django 4.2.7 on 2023-12-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
